; Default ini configuration

[Settings]
TimerIntervalMs=7              ; 0 to 10000
TimerIntervalAfterEnableMs=50  ; 0 to 10000
TimerToleranceMs=2             ; 0 to 10000
InputDelayFrames=0             ; 0 to 10
StartEnabled=1                 ; 0 (false) or 1 (true)
ProportionalPanning=0          ; 0 (false) or 1 (true)

; Set the available magnification factors
MagnificationCurve=1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.25, 5.0, 6.0, 7.0, 8.5, 10.0, 12.0, 15.0, 20.0, 26.0

[Keybinds] ; VK codes
ToggleMag=0x7C       ; F13 key
ZoomIn=0x7E          ; F15 key
ZoomOut=0x7D         ; F14 key
IncreaseLens=0x81    ; F18 key
DecreaseLens=0x80    ; F17 key
PanMouse=0x82        ; F19 key
TogglePanMouse=0x83  ; F20 key
